### ISSUE TITLE
What is this ? 

### ISSUE THREAD

**Issue by ZephirFXEC** [hakikat011/FluidSimulations-CUDA#1]
This repo is AI generated, the code is obviously wrong, and your paper state things you *haven't* achieved.

**Comment by hakikat011** [comment]
yes actually but it was a method and not a paper because me and my friends just started self learning about this and we wanted to document , it was not intentioned to be set on a public read and also the AI generated Repo is just a code base where we practice on how physics solvers work , its not something that we want to release , it is just something that we try to mend and learn using project based learning to enhance what we learn , so we basically used AI ide to start working on functions to what we learn integration on systems , and i Totally agree the code is wrong because its uncomplete and just a placeholder for anything we do , its more like a notebook to use ......... and i just checked your work and that seems pretty awesome and It would be awesome if you could give any insights because we cant find much on it and also  THANKS for responding
